language: java
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
- provider: script
  script: "./gradlew bintrayUpload"
  skip_cleanup: true
  on:
    repo: hmcts/health-spring-boot-starter
    tags: true
env:
  global:
  - secure: G6dGPNc5BmEMZSe5uG+o90jboGxJNqHN+LfNHOXln8ND2l3fFPrU0OJjeR8G8Bku7Xd3zk8nRtTMgYe0LWjfMfAbF9HXVWK/4+IyqV61VFgDz9Nn+G1fvOkvFcezhpWOQecg9qgDMcMHlxgrBEqJZNQqRVQCb0Qigy2Pjtqdonqtw3iViEePkARjmugNYlIr9PkZsCyIrJ01qyVVIuLWBfMEa2lAug4c9wEqxgKyAkDPGXtv+s/Kc7QvGd9NR9PkcESMRoDjD1zyuBdBjv138Mw/zutLnM+5jsuZ1ew3HbHHUbSO0bkT3M9wX8i5SbyJFmoCiIhckaFVlh2sPowyNWqbuiJ4Mf0dtoQIvZi6U2pJPKLFKMmfpoiu/pZf7dLeeRF4bQn+ihECVlG9MB+mYLbrohdGuozAm7KDqTTe+V6tcAPpyA9Nby5aT1bEx5auufxFn9H+FpDiI3yi5ACZCc2ke2cfekD0yEwpqwZKOjYK8wX3gBZGOl/bPCopi1usz2rX+rfIGX4ef2sM1IGORYGKTBY8X0Sf/p7TRpb1G1kwTl6My0qmtmEbtcgki8YmYkfm16Lo8ATEwHQcyga85KqSRJ4pSHmT5ltLWLi3m5j++CmoRL9lf1fhdl/FYUbam7z4ETwOTYG9jYEmzZOYvub7W3nauiueT91dVQG4JtQ=
  - secure: G1/kuJ49ElDmquMg4fP4lz4/k6yDBaRKMV4Scgw2ltbN7Qtdiuinl75BU7FAKPrRm6M3q9xOf1xZW9XGWqaiyChc8QZmf+PH4vDbmVzQvYWgcRvUIp6BbT9wnHSnnTgioA2li0vQaAdpgy6LB8jXyZove1MiTK6gEXdjJMREgDPNWK00H6aAk83INNygYlaMxAckEOxLQxJzorU4IKlJffIrk+xVlpqmZoVgxaw0VezGdseiE5LRu4fkjTbQdjpqh1pJM/lguBRkiQJrupujaTcXYkZWshphqO7j/rYzuMvCZ7Hp7vBNGspDA9BTjCWUHaiq9T/9ZVofz5UBke1QF4Rp/VJ7YyL6oa44F1EedZZyTCUQc2oj7vGTVwNTxGPP7Z4o/XomVb6cImXxHyVPZysT4FxLPMZZ1En4bc4y09g78GhjRmpdntOW5AeClD6a12hBsJiS+KbyaZ6AM+LwNXexZc27BEjSXB9acihl9cMbBAvHkpyqhsE8LLiqxftB6SQJppzk0AFYoeo/N+7FmF77f/1NEKBjHQc2AJKLDe4EfHSZ7mgPc8okiYxiUxzCe9wxIXHtK6i0UNfaLmi6iLnZGWQqayCrGT1CWWe83SLZ6zcHvegeZqBc48woDwL7yYS3UXvS3pcSlgyY4Qf+i60Ql8QVybALvooPogQd8uo=
